[workspace]
resolver = "3"
members = [
    "GitLinden",
    "crates/*"
]

[workspace.package]
edition = "2024"
version = "0.0.1"

[workspace.dependencies]
git = { path = "crates/git" }
git2 = "0.20.3"
iced = "0.14.0"
springtime-di = "1.0.4"
