[package]
name = "GitLinden"
version.workspace = true
edition.workspace = true

[dependencies]
git.workspace = true
iced.workspace = true
shaku.workspace = true
slint.workspace = true

[build-dependencies]
slint-build.workspace = true
